### ISSUE TITLE
正好有用 赞！

### ISSUE THREAD

**Issue by obrua** [MuGuiLin/QRCode#1]

**Comment by obrua** [comment]
不过我试了下，按了扫一扫没反应~~

**Comment by obrua** [comment]
扫一扫不是调用摄像头识别吗？

**Comment by MuGuiLin** [comment]
你好，我刚刚下载Vue版并安装后测试，是可以正常使用的！！扫一扫是需要调用摄像头才能识别的哦，并且在调用时要开启"允许使用摄像头“的权限才行。
