### ISSUE TITLE
是否存在非https不能用的情况，现在很多都是要求https或者localhost，不然会报错

### ISSUE THREAD

**Issue by sunnyday69** [MuGuiLin/QRCode#10]
如果不支持会提示Camera access is only supported in secure context like https or localhost【仅在 https 或 localhost 等安全上下文中支持摄像头访问】

**Comment by MuGuiLin** [comment]
这是由于浏览器本身做的限制哦！(就类似于HTML5中的 video 和 audio 标签一样，被浏览器限制为不能自动播放！！)
