### ISSUE TITLE
打包运行后图片无法显示

### ISSUE THREAD

**Issue by jinlongyu60** [MuGuiLin/QRCode#6]
打包为dist，使用serve -s dist在本机可运行；但在另一台电脑运行时二维码图片无法正常显示，并出现Uncaugt(in promise) image load Error错误

**Comment by MuGuiLin** [comment]
你好，你是用的生成二维码，还是识别二维码功能呀？如果是使用识别二维码的话， 在项目打包后，需要在https的域名下才能正常使用哦！

**Comment by jinlongyu60** [comment]
您好，识别二维码获取二维码实际内容这一功能是正常的，但是通过内容在网页显示是异常的，如图所示：
![Uploading 168a9cc63e2c0a792cedea6c24c1d90.jpg…]()
![2da9ee24face0f89090fcc12b2356f0](https://user-images.githubusercontent.com/19258936/130383580-345092aa-512d-4d4b-ae06-a1f50c0a5b85.jpg)

**Comment by jinlongyu60** [comment]
![168a9cc63e2c0a792cedea6c24c1d90](https://user-images.githubusercontent.com/19258936/130383725-33a62e9b-3e60-4545-9af9-570f4bded39e.jpg)

**Comment by MuGuiLin** [comment]
你好，打包后要在Web服务器环境下才能正常运行哦。

**Comment by jinlongyu60** [comment]
嗯嗯确实是，谢谢
